// index.js

const facts = {
  node: [
    "Node.js was created by Ryan Dahl in 2009.",
    "Node.js uses the V8 JavaScript engine from Chrome.",
    "Node.js is single-threaded but uses libuv to handle asynchronous operations.",
    "npm was created as the default package manager for Node.js.",
    "Node.js allows JavaScript to run outside the browser.",
    "Node.js is an open-source, cross-platform runtime environment for developing server-side applications.",
    "It uses an event-driven, non-blocking I/O model.",
    "Node.js is ideal for building scalable network applications.",
    "The Node.js package ecosystem, npm, is the largest ecosystem of open source libraries.",
    "Node.js applications are written in JavaScript.",
    "Node.js can be used to build real-time applications like chat apps.",
    "It supports the creation of RESTful APIs.",
    "Node.js has a built-in HTTP module to create web servers.",
    "It can be used with databases like MongoDB and MySQL.",
    "Node.js is maintained by the OpenJS Foundation.",
    "It supports modules using CommonJS module system.",
    "Node.js has a REPL (Read-Eval-Print Loop) for interactive testing.",
    "It can be used for building command-line tools.",
    "Node.js has a large and active community.",
    "It supports asynchronous programming using callbacks, promises, and async/await.",
    "Node.js can be used with TypeScript.",
    "It is suitable for microservices architecture.",
    "Node.js has built-in support for file system operations.",
    "It can be used to build desktop applications with Electron.",
    "Node.js supports streaming data.",
    "It is used by companies like Netflix, LinkedIn, and Walmart.",
    "Node.js has a package manager called npm.",
    "It can be used to build serverless applications.",
    "Node.js supports WebSockets for real-time communication.",
    "It can be deployed on various platforms including AWS, Azure, and Heroku.",
    "Node.js has a fast startup time.",
    "It allows code sharing between server and client.",
    "Node.js supports clustering to utilize multiple CPU cores.",
    "It has a built-in debugger.",
    "Node.js can be integrated with build tools like Gulp and Grunt.",
    "It supports environment variables for configuration.",
    "Node.js can be used to build APIs for mobile applications.",
    "It has a vibrant ecosystem of frameworks like Express.js and Koa.",
    "Node.js supports unit testing with frameworks like Mocha and Jest.",
    "It can be used to build IoT applications.",
    "Node.js has a non-blocking event loop.",
    "It supports TLS/SSL for secure communication.",
    "Node.js can be used to build proxy servers.",
    "It supports child processes for parallel execution.",
    "Node.js has a global object called 'global'.",
    "It can be used to build data-intensive applications.",
    "Node.js supports buffer objects for binary data.",
    "It can be used to build applications with GraphQL.",
    "Node.js has a built-in 'util' module for utility functions.",
    "It supports ES6 and newer JavaScript features."
  ],
  javascript: [
    "JavaScript was created in just 10 days by Brendan Eich.",
    "Despite the name, JavaScript is not related to Java.",
    "JavaScript is the most-used programming language on GitHub.",
    "The first JavaScript engine was called SpiderMonkey.",
    "JavaScript initially only ran in browsers before Node.js was invented.",
    "JavaScript is a multi-paradigm language supporting object-oriented, imperative, and functional programming styles.",
    "It is dynamically typed and interpreted.",
    "JavaScript runs in all modern web browsers.",
    "It can be used for both client-side and server-side development.",
    "JavaScript supports first-class functions.",
    "It has prototypes instead of classes for inheritance.",
    "JavaScript supports closures.",
    "It can manipulate the Document Object Model (DOM) in web pages.",
    "JavaScript supports asynchronous programming with promises and async/await.",
    "It has a strict mode to enforce better coding practices.",
    "JavaScript can be used to build mobile applications using frameworks like React Native.",
    "It supports regular expressions for pattern matching.",
    "JavaScript can be used to create games.",
    "It has a built-in Math object for mathematical operations.",
    "JavaScript can interact with HTML5 APIs like Canvas and Web Storage.",
    "It supports modules using ES6 module syntax.",
    "JavaScript can be transpiled from TypeScript.",
    "It has a large ecosystem of libraries and frameworks.",
    "JavaScript can be used to build desktop applications with Electron.",
    "It supports event-driven programming.",
    "JavaScript can be used with WebAssembly for high-performance applications.",
    "It has a built-in JSON object for parsing and stringifying JSON data.",
    "JavaScript supports destructuring assignment.",
    "It can be used to build progressive web apps (PWAs).",
    "JavaScript has a built-in Date object for handling dates and times.",
    "It supports template literals for string interpolation.",
    "JavaScript can be used to create browser extensions.",
    "It supports arrow functions for concise function expressions.",
    "JavaScript can be used with WebSockets for real-time communication.",
    "It has a built-in Set and Map objects for data structures.",
    "JavaScript supports the spread and rest operators.",
    "It can be used to build single-page applications (SPAs).",
    "JavaScript has a built-in console object for logging.",
    "It supports default parameters in functions.",
    "JavaScript can be used with GraphQL for API development.",
    "It supports optional chaining and nullish coalescing operators.",
    "JavaScript can be used with WebGL for 3D graphics.",
    "It has a built-in Intl object for internationalization.",
    "JavaScript supports generators and iterators.",
    "It can be used to build chatbots.",
    "JavaScript has a built-in Symbol type for unique identifiers.",
    "It supports BigInt for large integers.",
    "JavaScript can be used with service workers for offline capabilities.",
    "It supports dynamic import for code splitting.",
    "JavaScript can be used to control hardware with platforms like Johnny-Five."
  ],
  npm: [
    "npm stands for Node Package Manager.",
    "npm was created in 2010 by Isaac Z. Schlueter.",
    "You can install packages globally or locally using npm.",
    "npm has over 2 million packages available.",
    "The npm registry is the largest software registry in the world.",
    "npm is the default package manager for Node.js.",
    "It allows developers to share and reuse code.",
    "npm uses a package.json file to manage project dependencies.",
    "It supports semantic versioning for package versions.",
    "npm can run scripts defined in package.json.",
    "It has a command-line interface (CLI) for managing packages.",
    "npm can audit packages for security vulnerabilities.",
    "It supports scoped packages for organization-specific modules.",
    "npm can install packages from Git repositories.",
    "It supports private packages for proprietary code.",
    "npm can be used to publish packages to the registry.",
    "It has a package-lock.json file to lock dependency versions.",
    "npm supports installing packages from tarballs.",
    "It can be configured using a .npmrc file.",
    "npm supports workspaces for managing monorepos.",
    "It can run tests and other scripts defined in package.json.",
    "npm supports caching to speed up installations.",
    "It can be used to update outdated packages.",
    "npm has a website to browse and search for packages.",
    "It supports installing packages with specific versions.",
    "npm can be used to uninstall packages.",
    "It supports installing packages as development dependencies.",
    "npm can list installed packages and their versions.",
    "It supports installing packages from local directories.",
    "npm can be integrated with continuous integration pipelines.",
    "It supports installing packages from URLs.",
    "npm can be used to manage front-end dependencies.",
    "It supports installing packages with peer dependencies.",
    "npm can be used to create and manage package scripts.",
    "It supports installing packages with optional dependencies.",
    "npm can be used to link packages for local development.",
    "It supports installing packages with bundled dependencies.",
    "npm can be used to audit and fix vulnerabilities.",
    "It supports installing packages with binary components.",
    "npm can be used to manage multiple versions of packages.",
    "It supports installing packages with post-install scripts.",
    "npm can be used to manage project configurations.",
    "It supports installing packages with preinstall scripts.",
    "npm can be used to manage project metadata.",
    "It supports installing packages with install scripts.",
    "npm can be used to manage project versioning.",
    "It supports installing packages with prepare scripts.",
    "npm can be used to manage project publishing.",
    "It supports installing packages with prepublish scripts.",
    "npm can be used to manage project dependencies efficiently."
  ]
};


function getRandomFact(category = "javascript") {
  const selected = facts[category.toLowerCase()];
  if (!selected) {
    throw new Error(`Unknown category: "${category}". Try one of: ${Object.keys(facts).join(", ")}`);
  }
  const index = Math.floor(Math.random() * selected.length);
  return selected[index];
}

module.exports = {
  getRandomFact,
  categories: Object.keys(facts)
};
